fixup! fixup! fixup! fixup! fixup! fixup! fixup! [IMP] add a github workflow that generates test databases used in CI

diff --git a/.github/workflows/generate-testdb.yml b/.github/workflows/generate-testdb.yml
--- a/.github/workflows/generate-testdb.yml
+++ b/.github/workflows/generate-testdb.yml
@@ -48,6 +48,20 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: "${{ inputs.python_version }}"
+      - name: Upload database dump to release
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          RELEASE_TAG=$(gh release list | jq '.[] | select(.name =="${{ inputs.release_name }}") .tagName')
+          if [ -z "$RELEASE_TAG" ]; then
+              echo release \"${{ inputs.release_name }}\" not found
+              exit 1
+          fi
+          echo $RELEASE_TAG
+          echo test > $VERSION.psql
+          echo gh release upload $RELEASE_TAG $VERSION.psql --clobber
+          gh release upload $RELEASE_TAG $VERSION.psql --clobber
+          exit 1
       - name: Install required packages
         run: |
           sudo apt update
@@ -90,10 +104,10 @@ jobs:
           env.cr.commit()
           EOF
           odoo -d $DBNAME --load-language=fr_FR --stop-after-init
-      - name: Dump database and push to release
+      - name: Dump database
         run: |
           pg_dump $DBNAME -Fc -f $VERSION.psql
-      - name: Upload database dump to releases
+      - name: Upload database dump to release
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
